In [100]:
import pandas as pd
import os

In [85]:
df = pd.read_csv('../data/interim/03-bank_marketing_cleaned.csv', sep=',')

In [86]:
df.head()

,age,education,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,...,month_may,month_nov,month_oct,month_sep,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,poutcome_nonexistent,poutcome_success
0,1.576735,1.0,0.100728,-0.822641,0.195458,-0.34958,0.648073,0.72254,0.886533,0.712464,...,1,0,0,0,1,0,0,0,1,0
1,1.675004,4.0,-0.478303,-0.822641,0.195458,-0.34958,0.648073,0.72254,0.886533,0.712464,...,1,0,0,0,1,0,0,0,1,0
2,-0.290377,4.0,-0.080219,-0.822641,0.195458,-0.34958,0.648073,0.72254,0.886533,0.712464,...,1,0,0,0,1,0,0,0,1,0
3,0.004430,2.0,-0.467963,-0.822641,0.195458,-0.34958,0.648073,0.72254,0.886533,0.712464,...,1,0,0,0,1,0,0,0,1,0
4,1.576735,4.0,0.338544,-0.822641,0.195458,-0.34958,0.648073,0.72254,0.886533,0.712464,...,1,0,0,0,1,0,0,0,1,0

In [87]:
df.columns

Index(['age', 'education', 'duration', 'campaign', 'pdays', 'previous',
       'emp.var.rate', 'cons.price.idx', 'cons.conf.idx', 'euribor3m',
       'nr.employed', 'y', 'job_blue-collar', 'job_entrepreneur',
       'job_housemaid', 'job_management', 'job_retired', 'job_self-employed',
       'job_services', 'job_student', 'job_technician', 'job_unemployed',
       'marital_married', 'marital_single', 'default_yes', 'housing_yes',
       'loan_yes', 'contact_telephone', 'month_aug', 'month_dec', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'day_of_week_mon', 'day_of_week_thu', 'day_of_week_tue',
       'day_of_week_wed', 'poutcome_nonexistent', 'poutcome_success'],
      dtype='str')

In [88]:
df.describe()

,age,education,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,...,month_may,month_nov,month_oct,month_sep,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,poutcome_nonexistent,poutcome_success
count,4.117000e+04,41152.000000,4.117000e+04,4.117000e+04,4.117000e+04,4.117000e+04,4.117000e+04,4.117000e+04,4.117000e+04,4.117000e+04,...,41170.000000,41170.000000,41170.000000,41170.000000,41170.000000,41170.000000,41170.000000,41170.000000,41170.000000,41170.00000
mean,1.905366e-16,4.239867,8.284200e-18,1.325472e-16,1.767296e-16,-8.836480e-17,-4.418240e-17,-5.611165e-15,1.104560e-15,8.836480e-17,...,0.334345,0.099514,0.017416,0.013845,0.206704,0.209303,0.196405,0.197498,0.863371,0.03335
std,1.000012e+00,1.643993,1.000012e+00,1.000012e+00,1.000012e+00,1.000012e+00,1.000012e+00,1.000012e+00,1.000012e+00,1.000012e+00,...,0.471767,0.299355,0.130816,0.116849,0.404946,0.406816,0.397283,0.398116,0.343459,0.17955
min,-2.255758e+00,1.000000,-1.248619e+00,-8.226408e-01,-5.148276e+00,-3.495800e-01,-2.216475e+00,-2.374974e+00,-2.225001e+00,-1.722279e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
25%,-7.817221e-01,3.000000,-7.212884e-01,-8.226408e-01,1.954582e-01,-3.495800e-01,-1.197969e+00,-8.650871e-01,-4.747633e-01,-1.312933e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.00000
50%,-1.921080e-01,4.000000,-3.180352e-01,-1.777426e-01,1.954582e-01,-3.495800e-01,6.480730e-01,2.992877e-01,-2.802925e-01,7.124638e-01,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.00000
75%,6.923133e-01,6.000000,4.005826e-01,4.671557e-01,1.954582e-01,-3.495800e-01,8.390429e-01,7.225397e-01,8.865326e-01,7.724243e-01,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.00000
max,3.050770e+00,6.000000,2.644324e+00,2.401851e+00,1.954582e-01,1.379212e+01,8.390429e-01,2.057943e+00,2.939280e+00,8.208539e-01,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000

In [89]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 41170 entries, 0 to 41169
Data columns (total 43 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   age                   41170 non-null  float64
 1   education             41152 non-null  float64
 2   duration              41170 non-null  float64
 3   campaign              41170 non-null  float64
 4   pdays                 41170 non-null  float64
 5   previous              41170 non-null  float64
 6   emp.var.rate          41170 non-null  float64
 7   cons.price.idx        41170 non-null  float64
 8   cons.conf.idx         41170 non-null  float64
 9   euribor3m             41170 non-null  float64
 10  nr.employed           41170 non-null  float64
 11  y                     41170 non-null  int64
 12  job_blue-collar       41170 non-null  int64
 13  job_entrepreneur      41170 non-null  int64
 14  job_housemaid         41170 non-null  int64
 15  job_management        41170 non-null  int64
 16  job_retired           41170 non-null  int64
 17  job_self-employed     41170 non-null  int64
 18  job_services          41170 non-null  int64
 19  job_student           41170 non-null  int64
 20  job_technician        41170 non-null  int64
 21  job_unemployed        41170 non-null  int64
 22  marital_married       41170 non-null  int64
 23  marital_single        41170 non-null  int64
 24  default_yes           41170 non-null  int64
 25  housing_yes           41170 non-null  int64
 26  loan_yes              41170 non-null  int64
 27  contact_telephone     41170 non-null  int64
 28  month_aug             41170 non-null  int64
 29  month_dec             41170 non-null  int64
 30  month_jul             41170 non-null  int64
 31  month_jun             41170 non-null  int64
 32  month_mar             41170 non-null  int64
 33  month_may             41170 non-null  int64
 34  month_nov             41170 non-null  int64
 35  month_oct             41170 non-null  int64
 36  month_sep             41170 non-null  int64
 37  day_of_week_mon       41170 non-null  int64
 38  day_of_week_thu       41170 non-null  int64
 39  day_of_week_tue       41170 non-null  int64
 40  day_of_week_wed       41170 non-null  int64
 41  poutcome_nonexistent  41170 non-null  int64
 42  poutcome_success      41170 non-null  int64
dtypes: float64(11), int64(32)
memory usage: 13.5 MB

In [90]:
df['age'].value_counts()

age
-0.879991    1947
-0.781722    1845
-0.683453    1832
-0.388646    1778
-0.486915    1757
-0.585184    1744
-0.978260    1714
-0.290377    1475
-1.076529    1453
-0.093839    1430
-0.192108    1407
 0.102699    1277
 0.004430    1161
 0.200968    1142
 0.495775    1102
 0.299237    1055
 0.594044    1030
 0.397506    1011
-1.174798    1001
 0.790582     979
 0.692313     927
 0.987120     875
-1.273067     850
 0.888851     839
 1.183658     779
 1.085389     754
 1.281927     733
 1.576735     703
-1.371336     698
 1.380196     684
 1.675004     646
 1.478466     646
-1.469605     598
 1.773273     576
 1.871542     463
-1.567874     462
 3.050770     421
 1.969811     283
-1.666143     226
-1.764412     137
-1.862681     102
 2.068080      73
-1.960950      65
 2.166349      62
 2.559425      57
 2.362887      57
 2.264618      55
 2.952501      47
 2.461156      44
-2.059219      42
 2.854232      34
 2.755963      33
-2.157488      28
 2.657694      26
-2.255758       5
Name: count, dtype: int64

Cambiamos 999 por -1 para que el modelo entienda que son clientes nuevos y no se confunda con un número gigante.
Esto evita que el algoritmo distorsione los promedios con datos de personas que nunca han sido contactadas.

In [91]:
df['pdays'] = df['pdays'].replace(999, -1)

Borramos esta columna porque no sabremos cuánto dura una llamada hasta que ya terminó; incluirla sería "hacer trampa".
Al quitarla, evitamos el Data Leakage y aseguramos que el modelo haga predicciones realistas.

In [92]:
df = df.drop(columns=['duration'])

Simplificamos el historial a un "sí" o "no" para saber rápidamente si el cliente ya conoce la marca.
Esto ayuda al modelo a capturar el efecto de la familiaridad del cliente de forma más directa.

In [93]:
df['contacted_before'] = (df['previous'] > 0).astype(int)

Medimos qué tan "pesados" somos con el cliente y ponemos un tope de 10 para que los casos exagerados no rompan el cálculo.
De esta forma controlamos los valores extremos (outliers) y mantenemos estable el aprendizaje del algoritmo.

In [94]:
df['campaign_intensity'] = df['campaign'] / (df['previous'] + 1)
df['campaign_intensity'] = df['campaign_intensity'].clip(0, 10)

Juntamos las deudas en una sola variable para ver, de un vistazo, si el cliente ya tiene el bolsillo comprometido.
Simplifica la información financiera para que el modelo identifique más fácil el nivel de endeudamiento total.

In [ ]:
df['has_loan_or_housing'] = (
    (df['loan_yes'] == 1) | (df['housing_yes'] == 1)
).astype(int)

In [96]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 41170 entries, 0 to 41169
Data columns (total 45 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   age                   41170 non-null  float64
 1   education             41152 non-null  float64
 2   campaign              41170 non-null  float64
 3   pdays                 41170 non-null  float64
 4   previous              41170 non-null  float64
 5   emp.var.rate          41170 non-null  float64
 6   cons.price.idx        41170 non-null  float64
 7   cons.conf.idx         41170 non-null  float64
 8   euribor3m             41170 non-null  float64
 9   nr.employed           41170 non-null  float64
 10  y                     41170 non-null  int64
 11  job_blue-collar       41170 non-null  int64
 12  job_entrepreneur      41170 non-null  int64
 13  job_housemaid         41170 non-null  int64
 14  job_management        41170 non-null  int64
 15  job_retired           41170 non-null  int64
 16  job_self-employed     41170 non-null  int64
 17  job_services          41170 non-null  int64
 18  job_student           41170 non-null  int64
 19  job_technician        41170 non-null  int64
 20  job_unemployed        41170 non-null  int64
 21  marital_married       41170 non-null  int64
 22  marital_single        41170 non-null  int64
 23  default_yes           41170 non-null  int64
 24  housing_yes           41170 non-null  int64
 25  loan_yes              41170 non-null  int64
 26  contact_telephone     41170 non-null  int64
 27  month_aug             41170 non-null  int64
 28  month_dec             41170 non-null  int64
 29  month_jul             41170 non-null  int64
 30  month_jun             41170 non-null  int64
 31  month_mar             41170 non-null  int64
 32  month_may             41170 non-null  int64
 33  month_nov             41170 non-null  int64
 34  month_oct             41170 non-null  int64
 35  month_sep             41170 non-null  int64
 36  day_of_week_mon       41170 non-null  int64
 37  day_of_week_thu       41170 non-null  int64
 38  day_of_week_tue       41170 non-null  int64
 39  day_of_week_wed       41170 non-null  int64
 40  poutcome_nonexistent  41170 non-null  int64
 41  poutcome_success      41170 non-null  int64
 42  contacted_before      41170 non-null  int64
 43  campaign_intensity    41170 non-null  float64
 44  has_loan_or_housing   41170 non-null  int64
dtypes: float64(11), int64(34)
memory usage: 14.1 MB

In [97]:
df

,age,education,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,...,month_sep,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,poutcome_nonexistent,poutcome_success,contacted_before,campaign_intensity,has_loan_or_housing
0,1.576735,1.0,-0.822641,0.195458,-0.349580,0.648073,0.722540,0.886533,0.712464,0.331714,...,0,1,0,0,0,1,0,0,0.000000,0
1,1.675004,4.0,-0.822641,0.195458,-0.349580,0.648073,0.722540,0.886533,0.712464,0.331714,...,0,1,0,0,0,1,0,0,0.000000,0
2,-0.290377,4.0,-0.822641,0.195458,-0.349580,0.648073,0.722540,0.886533,0.712464,0.331714,...,0,1,0,0,0,1,0,0,0.000000,0
3,0.004430,2.0,-0.822641,0.195458,-0.349580,0.648073,0.722540,0.886533,0.712464,0.331714,...,0,1,0,0,0,1,0,0,0.000000,0
4,1.576735,4.0,-0.822641,0.195458,-0.349580,0.648073,0.722540,0.886533,0.712464,0.331714,...,0,1,0,0,0,1,0,0,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41165,3.050770,5.0,-0.822641,0.195458,-0.349580,-0.752373,2.057943,-2.225001,-1.495121,-2.815523,...,0,0,0,0,0,1,0,0,0.000000,0
41166,0.594044,5.0,-0.822641,0.195458,-0.349580,-0.752373,2.057943,-2.225001,-1.495121,-2.815523,...,0,0,0,0,0,1,0,0,0.000000,0
41167,1.576735,6.0,-0.177743,0.195458,-0.349580,-0.752373,2.057943,-2.225001,-1.495121,-2.815523,...,0,0,0,0,0,1,0,0,0.000000,0
41168,0.397506,5.0,-0.822641,0.195458,-0.349580,-0.752373,2.057943,-2.225001,-1.495121,-2.815523,...,0,0,0,0,0,1,0,0,0.000000,0
41169,3.050770,5.0,0.467156,0.195458,1.670663,-0.752373,2.057943,-2.225001,-1.495121,-2.815523,...,0,0,0,0,0,0,0,1,0.174921,0

In [101]:
folder_path = '../data/interim/'
file_name = '04-bank_marketing-feature.csv'
full_path = os.path.join(folder_path, file_name)

In [102]:
df.to_csv(full_path, index=False)